### ISSUE TITLE
Run time error.

### ISSUE THREAD

**Issue by Yanatecho** [whphhg/vanillacoind-web-ui#3]
npm start
```
> vanillacoind-web-ui@0.1.0 start /home/username/vanillacoind-web-ui
> node ./bin/www
Vanilla WebUI viewable on 127.0.0.1:1721.
```

then I open web browser and go to 127.0.0.1:1721

```
GET / 304 3394.017 ms - -
GET /stylesheets/default.css 200 22.811 ms - 3401
GET /javascripts/timeseries.js 200 14.161 ms - 5948
GET /javascripts/rewards_per_day.js 200 13.107 ms - 2264
GET /images/vanilla.png 200 15.689 ms - 1891

/home/username/vanillacoind-web-ui/routes/index.js:1126
      promises.push(new Promise(function(resolve, reject) {
                        ^
ReferenceError: Promise is not defined
    at update (/home/username/vanillacoind-web-ui/routes/index.js:1126:25)
    at null._onTimeout (/home/username/vanillacoind-web-ui/routes/index.js:1238:7)
    at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)

npm ERR! Linux 3.19.0-49-generic
npm ERR! argv "node" "/usr/bin/npm" "start"
npm ERR! node v0.10.41
npm ERR! npm  v2.14.17
npm ERR! code ELIFECYCLE
npm ERR! vanillacoind-web-ui@0.1.0 start: `node ./bin/www`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the vanillacoind-web-ui@0.1.0 start script 'node ./bin/www'.
npm ERR! This is most likely a problem with the vanillacoind-web-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vanillacoind-web-ui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls vanillacoind-web-ui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/username/vanillacoind-web-ui/npm-debug.log
```

and this is log file

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/bin/npm', 'start' ]
2 info using npm@2.14.17
3 info using node@v0.10.41
4 verbose node symlink /usr/bin/node
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart vanillacoind-web-ui@0.1.0
7 info start vanillacoind-web-ui@0.1.0
8 verbose unsafe-perm in lifecycle true
9 info vanillacoind-web-ui@0.1.0 Failed to exec start script
10 verbose stack Error: vanillacoind-web-ui@0.1.0 start: `node ./bin/www`
10 verbose stack Exit status 8
10 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
10 verbose stack     at EventEmitter.emit (events.js:98:17)
10 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
10 verbose stack     at ChildProcess.emit (events.js:98:17)
10 verbose stack     at maybeClose (child_process.js:766:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
11 verbose pkgid vanillacoind-web-ui@0.1.0
12 verbose cwd /home/username/vanillacoind-web-ui
13 error Linux 3.19.0-49-generic
14 error argv "node" "/usr/bin/npm" "start"
15 error node v0.10.41
16 error npm  v2.14.17
17 error code ELIFECYCLE
18 error vanillacoind-web-ui@0.1.0 start: `node ./bin/www`
18 error Exit status 8
19 error Failed at the vanillacoind-web-ui@0.1.0 start script 'node ./bin/www'.
19 error This is most likely a problem with the vanillacoind-web-ui package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     node ./bin/www
19 error You can get information on how to open an issue for this project with:
19 error     npm bugs vanillacoind-web-ui
19 error Or if that isn't available, you can get their info via:
19 error
19 error     npm owner ls vanillacoind-web-ui
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]
```

ps aux | grep vanilla

```
username       6777  0.0  0.0  31308  2424 ?        Ss   20:39   0:00 SCREEN -d -S vanillacoind -m ./vanillacoind
username       6778  6.3  7.2 336780 291604 pts/13  Ssl+ 20:39   0:08 ./vanillacoind
```

**Comment by whphhg** [comment]
Hey,

It looks like you're using an older version of Node.js without native Promises support. The solution is to update your Node.js installation.

**Comment by Yanatecho** [comment]
npm start
```
> vanillacoind-web-ui@0.1.0 start /home/username/vanillacoind-web-ui
> node ./bin/www

Vanilla WebUI viewable on 127.0.0.1:1721.

GET / 304 2393.629 ms - -
GET /stylesheets/default.css 304 3.681 ms - -
GET /javascripts/timeseries.js 304 2.991 ms - -
GET /javascripts/rewards_per_day.js 304 3.298 ms - -
GET /images/vanilla.png 304 0.903 ms - -
GET /stylesheets/dark.css 200 6.803 ms - 4935
GET /images/poloniex.png 200 1.734 ms - 688
/home/username/vanillacoind-web-ui/routes/index.js:1024
        cache.wallet_info = Object.assign({}, response[0].result, response[1].
                                   ^
TypeError: undefined is not a function
    at /home/username/vanillacoind-web-ui/routes/index.js:1024:36
    at IncomingMessage.<anonymous> (/home/username/vanillacoind-web-ui/node_modules/node-json-rpc/lib/rpcclient.js:182:9)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

npm ERR! Linux 3.19.0-49-generic
npm ERR! argv "/home/username/.nvm/versions/node/v0.12.0/bin/node" "/home/username/.nvm/versions/node/v0.12.0/bin/npm" "start"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! vanillacoind-web-ui@0.1.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vanillacoind-web-ui@0.1.0 start script 'node ./bin/www'.
npm ERR! This is most likely a problem with the vanillacoind-web-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls vanillacoind-web-ui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/username/vanillacoind-web-ui/npm-debug.log
```

I try,
- clear cache & cookie
- close all about vanilla
- uninstall all node module
- remove old nodejs
- delete vanillacoind-web-ui
- restart
- nvm default 0.12.0
- nvm use default (0.12.0)
- run vanilla
- clone vanillacoind-web-ui
- install node module again
- npm start
- open browser go to 127.0.0.1:1721

It still error.

```
node v0.12.0
npm  v2.5.1
```

I don't know why?

**Comment by whphhg** [comment]
The latest version of Node.js is 5.5.0, you're using 0.12.0. In 0.12.0 Object.assign is not supported, hence the error.

There's nothing else you need to do then update Nodejs to the latest version, that's it. :)

**Comment by Yanatecho** [comment]
Ohhhh.....Nooooooooooo...........!!!!!!
I do not use node.js, just two years to change the version that far these days. :P
It work, thank you. :)

**Comment by whphhg** [comment]
Goodie, glad it's working now. :-)
